#!/bin/bash
#this is a shortcut for pushing alx project to github

timestamp=$(date +"%Y-%m-%d %H:%M:%S")
commit_message="Commit with timestamp: $timestamp"
chmod u+x *-*
git add .
git commit -m "$commit_message"
git push
